apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  labels:
    app: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      labels:
        app: postgres-pod
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: db-container
        image: postgres
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: pv-storage
        env:
        - name: POSTGRES_PASSWORD
          value: example

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: postgres-pod
  ports:
  - port: 5432


