apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redi-deploy
  labels:
    app: redi-db
spec:
  selector:
    matchLabels:
      app: redi-pod
  template:
    metadata:
      labels:
        app: redi-pod
    spec:
      volumes:
      - name: pv-storage2
        persistentVolumeClaim:
          claimName: pv-claim2
      containers:
      - name: redi-container
        image: redis
        volumeMounts:
          - mountPath: "/var/lib/redis"
            name: pv-storage2
          - mountPath: "/usr/local/etc/redis/redis.conf"
            name: pv-storage2
---
#pas sur 
apiVersion: v1
kind: Service
metadata:
  name: redi-service
spec:
  selector:
    app: redi-pod
  ports:
  - port: 6379